#+TITLE: emacs.el
#+DATE: <2023-11-12 zo>
#+PROPERTY: header-args :tangle yes


#+begin_quote
Work in progress, there will be errors

Currently there is an issue with org-mode verions...
#+end_quote



* installation
#+begin_src emacs-lisp :tangle no :results silent
  (org-babel-tangle)
  (let ((dir (file-name-directory (buffer-file-name)))
	(target "~/.config/emacs-org/src"))
    (delete-file "~/.emacs.d/init.el")
    (make-directory "~/.config/emacs-org/" t)
    (cond
;     ((file-directory-p target) (delete-directory target t))
     ((file-symlink-p target) (delete-file target)))
    (make-symbolic-link dir target t)
    (make-symbolic-link (concat dir "init.el") "~/.emacs.d/init.el" t))
  (message "emacs conf bootstrapped, please relaunch emacs")
#+end_src

* init
#+begin_src emacs-lisp :tangle init.el
(when (version< "27" emacs-version)
  (message "version OK")
  (setq package-enable-at-startup nil))

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))


;; disable built-in org-mode
; (assq-delete-all 'org package--builtins)
; (assq-delete-all 'org package--builtin-versions)

;; fetch org-mode
(straight-use-package 'org)
(straight-use-package 'use-package)

(setq locale-coding-system 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(prefer-coding-system 'utf-8)

;; disable background mode
(use-package frame
  :bind
  ("C-z" . nil)
  ("C-x C-z" . nil))
#+end_src

#+begin_src emacs-lisp :tangle init.el
  (require 'org)
  (org-babel-load-file "~/.emacs.d/index.org")
#+end_src

* context  
throughout loading our configs we'll need to know whether to enable certain elements.  This sets up all predicates for any kind of selection we'll need.  We start off with a few indicators as to which kind of device we're dealing with. 
#+begin_src emacs-lisp
(require 'package)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
    (package-initialize)

      (intern "my/phone")
        (intern "my/laptop")
        (intern "my/uconsole")
        (intern "my/boox")
        (intern "my/unknown")
#+end_src

#+begin_src emacs-lisp
  (defconst my/device-type
    (let ((phone (file-exists-p "~/.DEVICE_PHONE"))
	  (boox (file-exists-p "~/.DEVICE_BOOX"))
	  (hostname (system-name)))
      (cond
       (phone 'my/phone)
       (boox 'my/boox)
       ((string= hostname "fajid-clocky") 'my/uconsole)
       ((string= hostname "jeroen-XPS-9320") 'my/laptop)
       (t 'my/unknown))))

  (defun my/device-phone-p ()
    (eq my/device-type 'my/phone))

  (defun my/device-laptop-p ()
    (eq my/device-type 'my/laptop))

  (defun my/device-boox-p ()
    (eq my/device-type 'my/boox))

  (defun my/prefer-light-p ()
    (my/device-boox-p))

#+end_src

We'll also want to know if there's a window manager available. 
#+begin_src emacs-lisp
(defun my/window-manager-p ()
  (and (display-graphic-p)
       (progn (when (get-buffer " *window-manager*")
                (kill-buffer " *window-manager*"))
              (when (get-buffer " *window-manager-error*")
                (kill-buffer " *window-manager-error*"))
              (when (executable-find "wmctrl")
                (shell-command "wmctrl -m ; echo $?" " *window-manager*" " *window-manager-error*"))
              (eq nil (get-buffer " *window-manager-error*")))))
#+end_src


* org babel

We'll be loading different org files for parsing so let's make it easy and less error sensitive, so if one file fails, it won't take down the rest of the execution.

#+begin_src emacs-lisp
(defconst my/emacs-org-conf-basepath "~/.emacs.d/")

(defun my/emacs-org-load-file (filename)
  ""
  (condition-case err
      (org-babel-load-file (concat my/emacs-org-conf-basepath filename))
    ((debug error) (progn
                     (message (format "Error loading org-file: %S (%s)\n" err filename))
                   (with-current-buffer (get-buffer-create "*org-load-errors*")
                     (goto-char (point-max))
                     (insert (format "Error loading org-file: %S (%s)\n" err filename))
                     (insert (with-temp-buffer (backtrace) (buffer-string))))))))

#+end_src

* exwm

- config :: [[file:exwm.org][exwm.org]]
  
Code specific to exwm, should only be included at specific situations. 
  
#+begin_src emacs-lisp
  (when (and (not (my/device-phone-p))
             (display-graphic-p)
             (not (my/window-manager-p)))
    (message "exwm eligable to boot")
    (my/emacs-org-load-file "exwm.org"))
#+end_src

* generic
[[file:generic.org][generic.org]]
#+begin_src emacs-lisp
(my/emacs-org-load-file "generic.org")
#+end_src

* interface
[[file:interface.org][interface.org]]

#+begin_src emacs-lisp
(my/emacs-org-load-file "interface.org")
#+end_src

* org-mode
** Generic org-mode configuration
[[file:org.org][org.org]]
#+begin_src emacs-lisp
(my/emacs-org-load-file "org.org")
#+end_src

** org-mode calendar related
[[file:org-mode-agenda.org][org-mode-agenda.org]]
#+begin_src emacs-lisp
(my/emacs-org-load-file "org-mode-agenda.org")
#+end_src

* development
** Generic
[[file:development.org][development.org]]
#+begin_src emacs-lisp
(my/emacs-org-load-file "development.org")
#+end_src

** This Is Development
[[file:tid.org.gpg][tid.org (gpg encrypted)]]

This file is likely to contian some configuration that is does not concern anyone outide the company, so i'll leave this outside git, and encrypted on disk. 
#+begin_src emacs-lisp
(my/emacs-org-load-file "tid.org.gpg")
#+end_src

* Other
[[file:other.org][other.org]]

#+begin_src emacs-lisp
(my/emacs-org-load-file "other.org")
#+end_src

* Device specific
#+begin_src emacs-lisp
(when (my/device-laptop-p)
  (my/emacs-org-load-file "device/laptop.org"))
#+end_src

* Scratch
#+begin_src emacs-lisp
  (use-package denote
    :ensure t
    :straight t
    :config
    (setq denote-directory (expand-file-name "~/Documents/denotes/"))
    (setq denote-save-buffers nil)
    (setq denote-known-keywords '("emacs" "tid" "3d" "php" "lisp"))
    (setq denote-infer-keywords t)
    (setq denote-sort-keywords t)
    (setq denote-file-type nil) ; Org is the default, set others here
    (setq denote-prompts '(title keywords))
    (setq denote-excluded-directories-regexp nil)
    (setq denote-excluded-keywords-regexp nil)
    (setq denote-rename-confirmations '(rewrite-front-matter modify-file-name))

    ;; Pick dates, where relevant, with Org's advanced interface:
    (setq denote-date-prompt-use-org-read-date t))

#+end_src
