#+TITLE: New Website
#+DATE: <2023-11-13 ma>

#+BEGIN_PREVIEW
Last week I decided to breath new life into this domain with yet another try to maintain some kind of blog.  As I recently started venturing into Go, start working on some IoT related projects for my employer, and plan on joining the Advent of Code once again to test my Lisp skills I thought I would probably have more than enough to talk about.
#+END_PREVIEW

I did start some kind of blog last year.  A static site generated with Hugo using org-mode files.  Turns out I spent a lot of time trying to get it to work the way I wantend, was not overly pleased with the (mobile) theme, and lost interest in the process.  This time around I'd like to give it a try with native Emacs org-mode publishing, hand-baked CSS and a bit of literate coding.  The result can be found at the [[file:org-publish.org][org-publish]] post, which will be the driving force behind this site.  Whenever I want to make changes to the theme, change settings, add categories... I will have to visit this specific org-mode file and edit it.  This means it will be always up to date with the latest changes.

Next to this I also intent on rewriting my current emacs+exwm configuration.  Currently its one big mess of source blocks in a org-mode file, with next to no structure and documentation.  It has reached a point where booting into my system has a 50/50 chance of succeeding.  I think the config is both bloated and filled with stuff I really dont need.  The lack of structure prevents (or rather: discourages) me from fixing things.  It also makes it pretty hard to replace things like LSP with Eglot as my LSP configs are all over the place.  You will be able to find them on the emacs category.  This file - which will probably link to multiple other configuration files - will also serve as my configuration.  So whenever I change something, this site will be updated as well to reflect those changes.

So... this website will host at least two living documents: my current emacs-configuration and my current static-site generator using org-publish.  As they are living /public/ documents I intent to keep them as up to date and well documented as possible.  This way I hope to help other people configuring their emacs to their needs, and/or to help people who want to publish their own blog the same way I'm doing right here.  I know i'm pretty bad at doing this whole social media stuff so don't expect an overload of posts,  but at least I'll get my configs out in the open, which is probably good enough for me. 
   
